### PR TITLE
README.md changes

### PR DESCRIPTION
**Pull request by Kwelp**

### CODE REVIEW

**Comment by ElaXan** [comment]
Pull Request to [Update Branch](https://github.com/Score-Inc/GCAndroid/tree/Update)

**Comment by ElaXan** [comment]
Read my [previous chat](https://github.com/Score-Inc/GCAndroid/pull/6#issuecomment-1292869068)

**Comment by ElaXan** [comment]
Fix your conflict

**Comment by Kwelp** [comment]
> Fix your conflict

I will.

**Pull request merged**
